language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_PACKAGE="Django>=1.5,<1.6"
install:
  - pip install $DJANGO_PACKAGE --use-mirrors
  - make travis
script: make test
notifications:
  irc: "irc.freenode.org#opps"
  on_success: "never"
